name: Promote stage

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      piper-version:
        required: false
        type: string
        default: 'latest'
      sap-piper-version:
        required: false
        type: string
        default: 'latest'
      on-productive-branch:
        required: true
        type: string
      is-optimized-and-scheduled:
        required: true
        type: string
      active-stages-map:
        required: true
        type: string
      active-steps-map:
        required: true
        type: string
      pipeline-env:
        required: true
        type: string
    outputs:
      pipeline-env: 
        value: ${{ jobs.Promote.outputs.pipelineEnv }}
env:
  PIPER_ACTION_PIPER_VERSION: ${{ inputs.piper-version }}
  PIPER_ACTION_SAP_PIPER_VERSION: ${{ inputs.sap-piper-version }}
  PIPER_ACTION_GITHUB_TOOLS_TOKEN: ${{ secrets.GH_TOOLS }}
  PIPER_vaultAppRoleID: ${{ secrets.PIPER_VAULTAPPROLEID }}
  PIPER_vaultAppRoleSecretID: ${{ secrets.PIPER_VAULTAPPROLESECRETID }}
  PIPER_ACTION_PIPELINE_ENV: ${{ inputs.pipeline-env }}
jobs:
  Promote:
    runs-on: self-hosted
    environment: 'Piper Promote'
    if: |
      fromJSON(inputs.active-stages-map).Promote == true &&
      inputs.is-optimized-and-scheduled == 'false' &&
      inputs.on-productive-branch == 'true'
    outputs:
      pipelineEnv: ${{ steps.pipelineEnv.outputs.pipelineEnv }}
    steps:
      - uses: actions/checkout@v3
      - name: sapCallStagingService
        if: fromJSON(inputs.active-steps-map)[github.job]['sapCallStagingService'] == true
        uses: SAP/project-piper-action@master
        with:
          step-name: sapCallStagingService
          flags: --action promote
      - name: Read stage configuration
        uses: SAP/project-piper-action@master
        with:
          step-name: getConfig
          flags: --stageConfig --outputFile stage-config.json
      - run: |
          echo "lockPipelineRun=$(jq -j .lockPipelineRun stage-config.json)" >> $GITHUB_ENV
          echo "::notice::lockPipelineRun $(jq -j .lockPipelineRun stage-config.json)"
      - if: env.lockPipelineRun == 'true'
        run: |
          echo "::notice::Writing lock-run.json for productive branch"
          touch lock-run.json
      - name: sapCumulusUpload (release status info)
        if: |
          fromJSON(inputs.active-steps-map)[github.job]['sapCumulusUpload'] == true
        uses: SAP/project-piper-action@master
        with:
          step-name: sapCumulusUpload
          flags: --filePattern "**/release-status-*.json" --stepResultType .status-log/release
      - name: sapCumulusUpload (lock-run.json)
        if: | 
          fromJSON(inputs.active-steps-map)[github.job]['sapCumulusUpload'] == true && 
          env.lockPipelineRun == 'true'
        uses: SAP/project-piper-action@master
        with:
          step-name: sapCumulusUpload
          flags: --filePattern "**/lock-run.json" --stepResultType root
      - name: Export pipeline environment
        uses: SAP/project-piper-action@master
        id: pipelineEnv
        with:
          step-name: ''
          export-pipeline-environment: true
